### ISSUE TITLE
It's too hard to use

### ISSUE THREAD

**Issue by RmondJone** [nanoscopic/stf_ios_support#106]
It's too hard to use, too many steps, and a lot of dependent engineering

**Comment by nanoscopic** [comment]
Agreed. Don't use it. It's been revamped entirely as the stickied issue says. Use ControlFloor instead.

**Comment by nanoscopic** [comment]
Once again agreed it is a mess, but some work will be put in to make this work and clean it up some.

If you have a specific issue on the steps, feel free to open an issue describing where you are stuck.
