### ISSUE TITLE
FATA[0000] 2 invalid character '/' looking for beginning of object key string 

### ISSUE THREAD

**Issue by Immanuel-Codoid** [nanoscopic/stf_ios_support#114]
I've done all the other setup, but when I run using "./run" from"stf_ios_support" folder the "FATA[0000] 2 invalid character '/' looking for beginning of object key string "  error is thrown, I don't know why this issue is caused. Can someone help me out with this?. If some more details are needed I'm ready to share.  

Thanks in advance

**Comment by Immanuel-Codoid** [comment]
Also, I don't see my device in the STF server running in my local host.

**Comment by Immanuel-Codoid** [comment]
I have solved the issue that I mentioned above, I had made a mistake in the config.json file. But now once I ran "./run" the process is stuck in the "Process start - wdaproxy", and "WDA Running" is not getting started.

**Comment by linhvv12** [comment]
HI @Immanuel-Codoid. Have you run successful IOS on STF yet?.  You can show image web stf to mange devices STF. thanks

**Comment by Immanuel-Codoid** [comment]
I'm still stuck with the same issue @linhvv12 , did you sort the issue out?, able to run ios on STF?

**Comment by nanoscopic** [comment]
Was this ever resolved?

**Comment by nanoscopic** [comment]
I'm closing this issue as it was opened titled with the error you get when config.json has a typo in in and is not proper JSON. Please open a new issue for any additional issue if you still have it.
