### ISSUE TITLE
/bin/sh: ./Scripts/bootstrap.sh: No such file or directory

### ISSUE THREAD

**Issue by r66ad** [nanoscopic/stf_ios_support#95]
new WebDriverAgent has now only build.sh script. The bootstrap.sh doesn't exist anymore. 
The build is also not working on xcode 12.3 anymore.

https://github.com/appium/WebDriverAgent/pull/454

**Comment by nanoscopic** [comment]
Nice update; will change to address this. Thanks for submitting this issue.

**Comment by forum77alive** [comment]
I have this problem too

**Comment by mertmansuroglu** [comment]
How did you solve the issue?? Do you have any updates? Thanks

**Comment by mertmansuroglu** [comment]
Because I also face the same issue its showing unknown target and exit 1 message after writing build.sh

**Comment by dproskuin** [comment]
I have the same problem right now.

**Comment by AnushaVaddaji** [comment]
I have the same problem, getting the below error :
+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1

**Comment by Avan92** [comment]
have the same problem, getting the below error :

define_xc_macros
XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
case "$TARGET" in
echo 'Unknown TARGET'
Unknown TARGET
exit 1
#95
Failed setup on MacOS Big Sur

**Comment by mbilbiesi** [comment]
Hey guys ! You just need to remove this line https://github.com/DeviceFarmer/stf_ios_support/blob/master/Makefile#L205

**Comment by mithilesh777** [comment]
I also have same issue with Xcode 12.5,
+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1

**Comment by nileshordex** [comment]
I also have the same issue with Xcode 12.5.1,

+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1

**Comment by CarlosOlivaGbnt** [comment]
I have the same issue with Xcode 13.0

 define_xc_macros
 XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
 case "$TARGET" in
 echo 'Unknown TARGET'
 Unknown TARGET
 exit 1

**Comment by DrxWeb** [comment]
any update?

**Comment by KimEklund13** [comment]
When I run this with build.sh I also get this. Xcode version 13.3.1, macOS Monterey 12.3.1
`(cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent && ./Scripts/build.sh -d)`

+ define_xc_macros
+ XC_MACROS='CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
+ case "$TARGET" in
+ echo 'Unknown TARGET'
Unknown TARGET
+ exit 1

As far as I know, this is the only way I've been able to get webdriveragent installed on a simulator because simply launching appium w/ the standard desired capabilities is not installing webdriveragent like I think it should automatically.

**Comment by nanoscopic** [comment]
The PR by @mbilbiesi has been merged.

@KimEklund13 This project was never meant to work with simulators. Only real iOS devices are supported.

The PR addresses the issue the title of this ticket describes, so closing.
If there are additional issues being encountered now, please make a separate issue for those.
